# Generated by Django 5.2.7 on 2025-10-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='posts/')),
            ],
        ),
    ]
